import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useAuth0 } from "@auth0/auth0-react";
import Cookies from 'universal-cookie';
import Link from 'next/link'
import {useState, useEffect} from 'react'
import { CldImage } from 'next-cloudinary';
import { CldOgImage } from 'next-cloudinary';
import { useRouter } from 'next/router'
import 'react-responsive-modal/styles.css';
import { Modal } from 'react-responsive-modal';

const Blog: NextPage = () => {

  const router:any = useRouter()
  const blogId = router.query.id
  console.log(blogId)
  const[loading, setLoading] = useState(true)
  const[blog, setBlog] = useState<any[]>([])

  const [open, setOpen] = useState(false);
  const [sub, setSub] = useState("");

  const[style, setStyle] = useState({
    left: "-50"
  })

  function openfunc() {
      setStyle({left: "0"})
  }

  function closefunc() {
      setStyle({left: "-50rem"})
  }

  const onOpenModal = () => setOpen(true);
  const onCloseModal = () => setOpen(false);

  async function addSub() {
    const res = await fetch('/api/subscribe', {
      method: 'POST',
      body: JSON.stringify({
        email: sub,
        message: "Add Subscription"
      })
    })
    const data = await res.json()
    setSub("")
    setOpen(false)
  }

 async function getBlog(id:any) {
    setTimeout(async (_id = id) => {
      if (_id != 'undefined') {
        console.log(_id)
        const res = await fetch('/api/getblog', {
          method: 'POST',
          body: JSON.stringify({
            blog: _id,
            message: "Blog Id sent"
          })
        })
        const data = await res.json()
        console.log(data)
        setBlog([data.blogs])
        setLoading(false)
      }
    }, 3000)
  }

  useEffect(() => {
    getBlog(blogId)
  }, [blogId])

  if (loading) {
    return(
      <div className={styles.loader}>
        <Head>
          <title>Loading...</title>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Image src="/spinner.gif" alt="Replit Logo" width={200} height={200} />
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Buzzbloggers - blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <div className={styles.navContain}>
        <h1 onClick={closefunc}>BuzzBloggers <Image src="/replit.svg" alt="Replit Logo" width={20} height={20}/></h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
        <button onClick={openfunc}>&#9776;</button>
        <Modal open={open} onClose={onCloseModal} center>
          <h2>Enter your email to subscribe!</h2>
          <input value={sub} onChange={(e:any) => {setSub(e.target.value)}} type="email" className={styles.modalinp} placeholder='Enter your email'/>
          <button onClick={addSub} className={styles.modBtn}>Subscribe!</button>
        </Modal>
      </div>

      <div style={style} className={styles.mobileNav}>
        <h1 onClick={closefunc}>X</h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
      </div>
    </div>

      <div>
        {blog ? blog.map((blog) => {
          const parsedimg = blog ? JSON.parse(blog?.image) : ""
          return(
            <div key={blog._id}>
            {blog ? <div className={styles.blogContent}>
              <h1>{blog.title}</h1>
              <p>{blog.postedon}</p>
              <h2>{blog.description}</h2>
              <CldImage
                width="1300"
                height="800"
                src={parsedimg.public_id}
                sizes="100vw"
                alt="Description of my image"
              />
              <h3>{blog.content}</h3>
              </div> : "Loading"}
           </div>
          )
        }): ""}
      </div>

      <div className={styles.ctaSect}>
        <h1>Connect with a community of more than 1000 bloggers by writing blogs!</h1>
        <h3>You can start your blogging career by practising here and getting an income side by side. If you are a nurturing blogger then you have landed on the correct page!</h3>

        <Link href="/write"><button>Start Writing Blogs...</button></Link>
      </div>
      
    

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 Buzzbloggers
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
           - All Rights Reserved. Made by Ehsan Saleem
        </a>
      </footer>
    </div>
  )
}

export default Blog
