import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAuth0 } from "@auth0/auth0-react";
import Cookies from 'universal-cookie';
import {useState, useEffect} from 'react'
import Link from 'next/link'
import { CldImage } from 'next-cloudinary';
import { CldOgImage } from 'next-cloudinary';
import 'react-responsive-modal/styles.css';
import { Modal } from 'react-responsive-modal';

const About: NextPage = () => {
  const cookies = new Cookies();
  const isUser = cookies.get('session')
  console.log(isUser)
  if (!isUser) {
    if (typeof window !== 'undefined') {
      window.location.href = '/';
    }
  }

  const [open, setOpen] = useState(false);
  const [sub, setSub] = useState("");

  const[style, setStyle] = useState({
    left: "-50"
  })

  function openfunc() {
      setStyle({left: "0"})
  }

  function closefunc() {
      setStyle({left: "-50rem"})
  }

  const onOpenModal = () => setOpen(true);
  const onCloseModal = () => setOpen(false);
  async function addSub() {
    const res = await fetch('/api/subscribe', {
      method: 'POST',
      body: JSON.stringify({
        email: sub,
        message: "Add Subscription"
      })
    })
    const data = await res.json()
    setSub("")
    if (typeof window !== 'undefined') {
      window.location.reload()
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Buzzbloggers - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <div className={styles.navContain}>
        <h1 onClick={closefunc}>BuzzBloggers <Image src="/replit.svg" alt="Replit Logo" width={20} height={20}/></h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
        <button onClick={openfunc}>&#9776;</button>
        <Modal open={open} onClose={onCloseModal} center>
          <h2>Enter your email to subscribe!</h2>
          <input value={sub} onChange={(e:any) => {setSub(e.target.value)}} type="email" className={styles.modalinp} placeholder='Enter your email'/>
          <button onClick={addSub} className={styles.modBtn}>Subscribe!</button>
        </Modal>
      </div>

      <div style={style} className={styles.mobileNav}>
        <h1 onClick={closefunc}>X</h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
      </div>
    </div>
    
      <div className={styles.about}>
        <h1>Our Story!</h1>
        <p>Laborum ullamco veniam nisi eiusmod duis esse et officia. Nisi velit ad excepteur in minim incididunt incididunt consectetur. Dolore aute duis nostrud esse laboris nulla. Lorem adipisicing culpa veniam esse. Ea nisi mollit magna ullamco cupidatat nostrud. Tempor voluptate duis laborum velit in officia consectetur labore proident. Id reprehenderit ea minim velit ipsum adipisicing mollit veniam. Tempor Lorem laborum officia consectetur. Nostrud consectetur eu aliqua sit enim tempor duis culpa occaecat. Ipsum do sint velit laborum incididunt. Occaecat culpa in excepteur et quis minim reprehenderit amet et. In incididunt laboris esse laborum ullamco minim laboris. Mollit fugiat aliqua consectetur non aute. Incididunt quis incididunt anim ut aliqua do. Incididunt sit tempor esse velit sunt voluptate commodo consectetur. Labore eiusmod aliquip consequat proident commodo anim id. Minim ex duis sint id sunt aute eiusmod. Esse exercitation deserunt ea cillum consectetur. Anim occaecat minim magna velit duis aute do commodo duis.</p>

        <p>Consectetur aute labore elit est anim ea non eiusmod labore. Officia commodo excepteur ad ipsum eiusmod sint. Cupidatat proident pariatur exercitation proident quis aliquip. Esse fugiat ullamco magna nostrud sit. Culpa duis labore exercitation occaecat. Cillum voluptate minim qui ad. Pariatur deserunt labore voluptate eiusmod sunt. Id et consectetur aute deserunt do sunt deserunt minim nisi. Ex nostrud proident consequat incididunt non. Ut nisi duis laboris incididunt occaecat voluptate magna velit fugiat. In incididunt consectetur dolor ea aute aliquip amet magna. Magna occaecat sit nulla et velit fugiat. Occaecat aliqua ad adipisicing laborum cillum consectetur sunt deserunt. Proident nisi tempor esse ea do. Voluptate excepteur velit aliqua eu labore fugiat irure. Cillum est excepteur reprehenderit proident. Ad aute occaecat non aliquip sint quis sit. Sit id tempor nisi occaecat incididunt. Est officia in ex ex ullamco voluptate occaecat dolor. Veniam incididunt officia ea magna. Ex voluptate eu elit aute elit velit ut amet. Et tempor culpa ut qui mollit nisi minim fugiat. Exercitation dolor minim consequat consectetur esse laborum est reprehenderit esse. Cillum sunt non tempor cupidatat id aute labore id aute. Pariatur quis irure non Lorem. Ea adipisicing ex eu est ullamco. Ex aute ex non exercitation ex voluptate adipisicing qui. Aliquip eiusmod adipisicing commodo sit ipsum Lorem consectetur ipsum. Est laborum non aliquip laboris consequat esse nisi esse cupidatat.</p>

        <p>Quis fugiat ex nisi magna ipsum. Tempor proident adipisicing occaecat Lorem non proident in. Proident Lorem cillum ut dolor enim ea. Elit incididunt cupidatat do qui est. Reprehenderit ullamco nulla pariatur pariatur duis sit commodo. Elit quis ullamco esse enim. Velit Lorem nostrud minim ipsum elit nulla. Occaecat aute in nostrud ea id cupidatat dolor. Enim tempor voluptate officia elit dolore. Commodo qui deserunt deserunt minim officia sint. Eiusmod culpa irure minim nulla consequat aute est dolore. Velit aliqua eu nisi do. Labore proident adipisicing aliquip commodo duis. Officia velit occaecat reprehenderit cillum elit sint Lorem dolor occaecat. Lorem occaecat enim in mollit incididunt ut commodo aute. Sit culpa elit sit ex reprehenderit tempor anim. Non cupidatat reprehenderit aliqua do consectetur. Laborum dolore sit nostrud labore proident. Magna sint eiusmod eu aliquip magna. Ad excepteur id minim laborum. Et reprehenderit qui et aliquip. Quis amet voluptate et et incididunt non dolore veniam. Qui cillum proident sit eu.</p>

        <p>Pariatur sint ipsum aliqua excepteur deserunt cillum eu ad ad. Culpa nostrud esse duis non cillum. Elit culpa ea velit aliqua. Reprehenderit mollit voluptate nisi Lorem ullamco. Eiusmod ullamco cillum laboris Lorem aute do. Amet minim ad mollit elit aliqua aute ullamco tempor pariatur. Aliquip mollit duis ipsum excepteur Lorem. Est sint commodo duis incididunt aute minim laboris consectetur. Commodo non ut consequat laboris id. Sint quis pariatur dolore elit reprehenderit velit. Excepteur esse dolor labore nostrud aliqua pariatur. Aliqua officia duis do labore. Duis eu nulla dolor Lorem cupidatat nostrud. Elit elit est nulla sint qui incididunt voluptate velit. Pariatur culpa exercitation eu labore do voluptate officia. Veniam qui ad aute adipisicing ex. Amet id elit non dolor anim quis. Aute deserunt sit aliqua cillum cillum laborum. Magna reprehenderit reprehenderit in irure sunt proident. Et consectetur esse eiusmod laborum cupidatat. Non id duis in ex. Consequat nostrud commodo ullamco fugiat aliqua aute incididunt reprehenderit. Magna fugiat ullamco aliqua duis incididunt ullamco ea. Eiusmod magna fugiat quis ex. Anim nisi enim proident sint esse proident. Eiusmod cupidatat reprehenderit esse id anim. Elit aute anim do commodo.</p>

        <p>Aliqua irure irure aute ipsum reprehenderit reprehenderit ad aliqua ullamco. Anim laborum consequat dolor quis aliquip ad occaecat aliqua duis. Pariatur mollit incididunt esse ex Lorem do nulla laborum officia. Dolor do pariatur ipsum ad. In ex cillum fugiat laborum. Cupidatat ea ullamco esse reprehenderit duis. Amet proident id ea officia exercitation minim ea quis. Irure quis quis sit aliqua adipisicing mollit eu. Cillum aliquip ex nostrud occaecat ea. Id consectetur sint deserunt aute duis cillum. Laborum ut deserunt dolor dolor Lorem ex. Ex non non adipisicing quis nisi anim laborum. Excepteur ut aliquip non elit do. Id adipisicing duis reprehenderit consequat adipisicing et minim occaecat. Duis dolore excepteur incididunt reprehenderit consequat. Commodo fugiat magna esse magna laborum ex proident fugiat cillum. Consequat et in exercitation tempor aute deserunt enim ex id. Labore nostrud tempor exercitation fugiat quis ut amet. Exercitation ullamco esse enim incididunt exercitation labore irure do. Magna tempor esse proident ad officia. Exercitation irure et nostrud nostrud. Commodo eiusmod ad excepteur occaecat. Pariatur esse mollit ea ea nulla ullamco officia. Excepteur aliquip consequat irure ex. Proident aliquip cillum eiusmod sint duis. Do fugiat aliqua cillum tempor fugiat. In reprehenderit esse sit eu velit irure. Cupidatat est ipsum sunt labore enim elit.</p>
      </div>

      <div className={styles.subSect}>
        <h1>Subscribe to our Email to get Daily updates of New Blogs</h1>
        <input value={sub} onChange={(e:any) => {setSub(e.target.value)}} placeholder="Enter your email to subscribe" />
        <button onClick={addSub}>Subscribe!</button>
      </div>

      <div className={styles.ctaSect}>
        <h1>Connect with a community of more than 1000 bloggers by writing blogs!</h1>
        <h3>You can start your blogging career by practising here and getting an income side by side. If you are a nurturing blogger then you have landed on the correct page!</h3>

        <Link href="/write"><button>Start Writing Blogs...</button></Link>
      </div>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 Buzzbloggers
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
           - All Rights Reserved. Made by Ehsan Saleem
        </a>
      </footer>
    </div>
  )
}

export default About
