import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import Cookies from 'universal-cookie';

const Signup: NextPage = () => {
  const[username, setUsername] = useState('')
  const[email, setEmail] = useState('')
  const[password, setPassword] = useState('')
  const cookies = new Cookies();
  const isUser = cookies.get('session')
  if (isUser) {
    if (typeof window !== 'undefined') {
      window.location.href = '/home';
    }
  }

  async function usersign(e:any) {
    e.preventDefault()
      const res = await fetch('/api/addUser', {
        method: 'POST',
        body: JSON.stringify({
          username: username,
          email: email,
          password: password
        })
      })
      const data = await res.json()
      cookies.set('session', data, { path: '/' })
      if (typeof window !== 'undefined') {
        window.location.href = '/'
      }
  }
  return (
    <div> 
    <div className={styles.container}>
      <Head>
        <title>Buzzbloggers - Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.flexC}>
        <div className={styles.imgSide}>
          <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0QDQ0NDQ0ODQ8PEA0RDQ0QDQ8NDQ0PFREWFhcRFRMYHTQgGxoqGxcVITEiJSkrMDouGCAzODMtNzQtLi4BCgoKDg0OGBAQGy0lICYtKy8wLS0tLSstMDAtLS0tLS0tLS0tKy0tLSsrLS0tLS0rLy0tKystLS0vLS0wLS8tLf/AABEIALEBHAMBEQACEQEDEQH/xAAaAAEBAAMBAQAAAAAAAAAAAAAAAQIEBQMH/8QAPRAAAgIBAgIHBAcGBgMAAAAAAAECAxEEIRIxBRNBUWFxgSIyUpEUQnKCobHBBiNTYmOSFTNDstHwJDRE/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAECAwT/xAAwEQEAAgECBAMIAgEFAAAAAAAAAQIRAyESMUFRYYGxEyIycZGh4fAE0cEjM0JSYv/aAAwDAQACEQMRAD8A+JlVs6uvgroj22Q62fjmTUV/as/eN2jFYjzcqTxWme2zUwYdTAFwBmggBAoBAAAABAAAAAAgAAAAAAIAAAAAAAAAgAABUBmwOh0quKvRWpezPTxh9+qUoSXyUX95G77xE+Dhoz716+Pru5+DDuYAuAM5Rw8d3PzEsxOYygVAAECoAAAAAEAAAIAAAAAAABAAAAAAAAAEAAVAe1tcoScJxlCS5xlFxkvNMM1tFozE5bnR2prcJaTUPgqnLjquw5PT3YxxNLdwawpLnsmuWHYnpLlqVtFuOnPrHeP77MNd0dbTjrI+zL/Lti1Om1d8LFtL/uRMTDVNWt+U79uv0a8Y5aS3beElu2+5IzzdJ2jMunHoyyqqy+yKUq3X+5yusrc88NlkecY5XJ75azhc+3BwxxTz7f28861b2ilevX5dIcxnF6ACFACAQKAQAAAAAIwIAAAAAAAAAgAAAAAAAACAVAdWrpq/hVdzWqq/hX5sUV/JP3oP7LRrinq4T/HpnNfdnvG34lhrdHW6/pGmcpU5Ssrk07dNN8oya96L7J4WeTwxMdYWl5zwX5+v72eOh6Q1NGeovsqUvejGT4JfajyfqSJmOS6mjTU+KMva79oNa04/SJQT59XGFLa8XBIvtLd3Ov8AF0azmK/5a/ReudNvG49ZCalC+ptpW1S96LfY+1PsaT7CROJdNTT464jy8JbPSOj6qUXCXWU2Lj09uMdZXnt7pJ7SXY15EmMJpanHG+0xzj96dmoR1QABCiAAIFAIAAgEAoACAAAAAAAAQAAAAAAAAAQGYGz0bqlVanNZrmnXfD46pe8vNc14pM1S2J8HLVpxV25xvHzYazTuq2ypvLhKUc9kkntL1WH6ktXhmYa078dYtDyo08rJTUWsxhOeH2qEeJpeOE36CtZtyLWiu8vEy06PRmvhGMtPqFKenm+J8OOsosxjra89uNmuTWz5JrVZ6S46mnMzF6c4+/hP7sz12ilU4vKsrms03xz1dsfDPJrti90+YmuGtPUi+3KY5x2apl0QABABRAAECoBGAAAAAEAAAAAAAAgAAAAAAAFQFAjA29fPinGT5uqji8+riv0N6k5nyhz0oxHnPq89FqXTfXclnhkm49ko8pR9VlepmtuG0SalOOs1ZdK6NVWtQfFVNKyifx1S91+fNPxTQvXE7JpX4q78+vzaRl0bug6SnUpQxG2mb/eUTy65+O28Zd0lhmq2w530otvynu3Y6Sq7fSWe0+eltlGNyfdCe0bF8n4GuGJ+H6Me0tT/AHI845efb0aVtcoycJxlCUdpQlFxlHzT3RiYmObtExaMwxSbaSTbfJJZbZMKs4OO0ljwez+RZiYSJieTEioUAEo497bw+t8i47pnPJ5N58F3EXChQAAAAAIAAAAAAABAAAAAAAVAAEYttRXNtJebCTOHS1Olpi31upi5bLgph1/DhYw55Ufk2dZrXrP0caXtPw128dmlbGp+7ZLw46+H8pM5zEdJdM26w29Dq63D6Lqs9Vluq6K4p6Wb5yS+tB7Zj6rfnYmMYlzvSYnjpz6x3/Pi8ukOi7aVGbSnXP8Ay763x0WfZn3/AMrw+9EmuGtPVrfaOfaebRwZdEA6FHTF6ioTcb61tGu+KtjFd0W94/daNxqTynf5uM6FZnMbT4bfvm3ul7lTiimuNFkq4S1TjKbalOKl1UXJtxik1lZ3eexHS9ojasY7uehWdT37TmOn9uLg4vWzpcc+25KPbwxUn8m0Ix1ZnONnrK+le7Cyf2pqK+SX6mvcZxeecw85amT2ilD7Kw/m9ycXZeHu81HvI0oUAAAAAAAAgAAAAAAAEAAAAACoCAZcDTeU01zTWGggwqAYsDa0Ov1FDbptlBS9+KxKuxd04P2ZLwaYiZjk5X0qX+KG1LpaEsdbodJN4w5xhbp5PxxXNRT+6Xi7wx7GYn3bz9p9Ymfu5mM5wsfoZd0cWB2f2ljnV22rLhfw31PvhbFSXyy4+cWjd+bz/wAWf9KK9YzE+UuU0Zeli0BFAIySCqAAgAAAAAAAACAAAAAAAAQAAAAVAb37PVKeu0cJY4ZaihST5Nca2LX4ocP5EzGleY7S8dVNzssnL3pznKXm5Nsk83SkYrEPFhtGBl1eEpS2z7sfrSXf4LxLjbMs53xDBv0XcRcIFMAVMDo6XXwdUdPqYynXDidNkMddp292kntKDe7i8b7prfOomMYlwtp2i3HTn1jpP58WNtGnW8dUpru6iyM/k9vxLw1/7fZYvedpr94ac8Z2zjx5mJdY8UCgAAAAgAAAAAAAACAAAAAAAAQAAAqAz0t8qrK7Ye9XOE492YvK/IRON2b1i1ZrPV0emaYxvlOvem799Q/6c23w+cXmL8Yst4xLloWmaYnnG0/vjzc9ojs99LUsTtsWa6+Hb+JY88MPwbfgmbrXrPJi9t4rHOWtbNyk5SeW+ZmZzu3EREYhhgigAABUBkAAAAAAAAAgAAAAAAAACAAAAAAAAQABUBAN7R66Kr6i+LnTlyg4462ib5yhnbD2zF7PC5Pc1W0crcnG+nOeKnP7T80u08UnKu2u2O7ypKE0l3wlvnyyvETTtOVrfO0xif3q9OkVwU6Wn+n18/GdvL5QUPmzV9q1r5/VnS961reOPp+XPObuAAAAABUBQAAAAAAAAEAAAAAAAAAQAAAAAAACAVAJJrKaw1s09mmEdB6SD00b6nJuDUNTXLDcJSb4bI4+o+W/JrxRcbZhzi8xfgt5f18/8NCyKwZdHR6filqWlyVOjS8vo1eDpqfE4/xpmdOJnx9Zc4w7gAAAAAVAAAAAAAAAAACAAAAAAAAAIAAAAAAABUB0OsWpSjP/ANhLELH/APQvgm/j7pdvJ9jOuePaefq4Y9ny+Ht2+XgvQcv/ACFTLaOoUtPNY+PaL9J8Evuk0/ixPXY/kR7nFHTf6fhzrH2b+Jzl2dPpiPFDR6hcrdPXCT/qU/umv7Ywf3jVt8S4aG03rPSftO7mmXoAAAAAwAwAAAAAAAAAAAAEAAAAAAAAAQAAAAAAFQEA6Wknx36a7tVtfXdntRkpcfqk35pnWu9os894xS1fDZzbJcTlLvbfzZzmczl2rGIiHU6Hkrqp6GTSlKXW6RtpL6RjDqy+SnHC+1GHiWN9nDV9y0akfKfl38vTLQlBptNNNNpprDTXNNd5l6InO8JgBgBgBgDKEMvHq32JdrYiMpM4Yye+3Ls8hKwxCgAAAAAAAAAAAgAAAAAAAACAAAAABUBiwPbTWNcaX1oyX4f8ZXqarOGLxnEvIy2xaIjtR1NWrSV9kadUsJaiWep1K5JXNe7P+fk/rfEbzxc+bzcNtH4YzXt1j5eHh9GprNFbTJRurlW2sxzvGa+KMltJeKbRmYmObtTUreM1nLwwRsA2KNHOUes2hV23T9mvyT+s/BZZuunM79O7nbUiJx17PO6yOOCvPDtxTaxKxrta7F3ITMRtC1rPOzwMuiAAAAAAAAAAAAAAgAAAAAAAACAAAACoDECxe680ElQoBi4kRuaLpbU0xcK7X1b3dUlG2lvvdck458cGotMOV9Gl5zMb9+r3/wAZi/e0Ojk+9V21Z9ITS/AvH4Qz7CcYi9vrn1P8Xn/p6bS0vskqeskvWxssamOUQewzztM+f9Yauo1FlkuO2yVkuScm3hdy7kZtabby60pWkYrGHkRsAAQAAAAAAAAAAAAAEAAAAAAAAAQAAAqAxAAZgAIAAqQGQAIAQKAAIAAAAAAAAAAAAACAAAAAAAAAIAAqA6rjoLdkrdDN8m5PU6b1244r+817s+Dzf61P/UfSf69Glrej7aZJWJcMk3XZGSnVbH4oTWzX5cnhkmJh109Wt42/MfN44I6AEAAWKCMiCFUCAECgAIgUAAAAAAAAAAAACAAAAAAAAAIBUBlkDd6P16gpU3RdmmsebILHFXLGFdW3ymvk1s9jVbY2nk46mnMzxV2tH7ifD0Ya/SOqxwbU1hSrsj7ttclmM14NfqiWjE4a078dctfBlswUWMM78kub8e5eJYhJlCKACCFUCAECgAIgUAAAAAAAAAAAACAAAAAAAAACAoEA6+kpnqNNwR4XZppezxTrrTosy8Zk0tprbf8A1GdYrN67dP39+by3vGlqZnlb1j8ejyfRlqftyor8ZarT/kpN/JE9lbriPNqP5FZjMZnyl5SVEfr9fLugpQqXnOSy/RLzJileuW4m9umHjOxy54WOSSxGPkjEzluIwxIqFAAQQqgQAgUABECgAAAAAAAAAAAAQAAAAAAACoCAQDd6Ofs6qL5SofzVkGvyN0na0eDlqRvWfFqqpeZzdGeAAAABCgAIIVQIAQKAAIAAAAAAAAAAAAACAAAAAAAqAxAgGzpXiFr+JRgvWSk/9v4monESxaMzCGGgCAAAACFAAQQqgQAgUABECgAAAAAAAAAAAAQAAAAAKgIEYhWxV7n3pflEvRj/AJKZaAAEAAADAhQABUCAAABAAAAAAAQKAQCgQCgQAAAAAAGSA//Z" />
          <div className={styles.abs}>
            <h1>Buzzbloggers <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} /> - The blog which engineers love!</h1>
          </div>
        </div>
        <div className={styles.btnSide}>
          <h1>Create An Account!</h1>
          <form onSubmit={usersign}>
            <input onChange={(e:any) => {setUsername(e.target.value)}} value={username} placeholder='Enter a unique username' type="text" />
            <input onChange={(e:any) => {setEmail(e.target.value)}} value={email} placeholder='Enter your email' type="email" />
            <input onChange={(e:any) => {setPassword(e.target.value)}} value={password} placeholder='Enter your password' type="password" />

            <button type='submit'>Signup</button>
            <p>Already have an account? <Link href='/'>Login</Link></p>
          </form>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 Buzzbloggers
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
           - All Rights Reserved. Made by Ehsan Saleem
        </a>
      </footer>
    </div>
  </div>)
}

export default Signup
