import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAuth0 } from "@auth0/auth0-react";
import Cookies from 'universal-cookie';
import Link from 'next/link'
import { CldUploadWidget } from 'next-cloudinary';
import 'react-responsive-modal/styles.css';
import { Modal } from 'react-responsive-modal';

const Write: NextPage = () => {
  const cookies = new Cookies();
  const isUser = cookies.get('session')
  console.log(isUser)
  if (!isUser) {
    if (typeof window !== 'undefined') {
      window.location.href = '/';
    }
  }

  const[title, setTitle]:any = useState('')
  const[content, setContent]:any = useState('')
  const[image, setImage]:any = useState()
  const[description, setDescription]:any = useState('')
  const[resource, setResource]:any = useState()

  async function addBlog() {
    const newblog = {
      title: title,
      description: description,
      image: JSON.stringify(resource),
      content: content,
      author: isUser.user._id,
    }

    const response = await fetch('/api/addblog', {
      method: 'POST',
      body: JSON.stringify(newblog)
    })
    const data = await response.json()
    console.log(data.message)
    setTitle("")
    setDescription("")
    setContent("")
    setResource()
    if (typeof window !== 'undefined') {
      window.location.reload()
    }
  }

  const [open, setOpen] = useState(false);
  const [sub, setSub] = useState("");

  const[style, setStyle] = useState({
    left: "-50"
  })

  function openfunc() {
      setStyle({left: "0"})
  }

  function closefunc() {
      setStyle({left: "-50rem"})
  }

  const onOpenModal = () => setOpen(true);
  const onCloseModal = () => setOpen(false);

  async function addSub() {
    const res = await fetch('/api/subscribe', {
      method: 'POST',
      body: JSON.stringify({
        email: sub,
        message: "Add Subscription"
      })
    })
    const data = await res.json()
    setSub("")
    setOpen(false)
  }

  console.log(resource ? resource : "undefined data resource")

  return (
    <div className={styles.container}>
      <Head>
        <title>Write a blog...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript">  
          </script>
      </Head>

      <div>
      <div className={styles.navContain}>
        <h1 onClick={closefunc}>BuzzBloggers <Image src="/replit.svg" alt="Replit Logo" width={20} height={20}/></h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
        <button onClick={openfunc}>&#9776;</button>
        <Modal open={open} onClose={onCloseModal} center>
          <h2>Enter your email to subscribe!</h2>
          <input value={sub} onChange={(e:any) => {setSub(e.target.value)}} type="email" className={styles.modalinp} placeholder='Enter your email'/>
          <button onClick={addSub} className={styles.modBtn}>Subscribe!</button>
        </Modal>
      </div>

      <div style={style} className={styles.mobileNav}>
        <h1 onClick={closefunc}>X</h1>
        <ul>
          <Link href="/home"><li>Home</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/write"><li>Write</li></Link>
          <Link href="/about"><li>Our Story</li></Link>
          <Link href="/account"><li>Account</li></Link>
        </ul>
        <div>
          <button onClick={onOpenModal}>Subscribe us!</button>
        </div>
      </div>
    </div>
      
      <div className={styles.formContain}>
      <input onChange={(e:any) => {setTitle(e.target.value)}} value={title} placeholder='Blog Title...' />
      <CldUploadWidget
        uploadPreset="ajiy2qfo"
        onSuccess={(result, { widget }) => {
          setResource(result?.info);
          console.log(resource)
          widget.close();
        }}
      >
        {({ open }) => {
          function handleOnClick() {
            setResource(undefined);
            open();
          }
          return (
            <button onClick={handleOnClick}>
              Upload an Image
            </button>
          );
        }}
      </CldUploadWidget>


      <input onChange={(e:any) => {setDescription(e.target.value)}} value={description} placeholder='Blog Description...'/>
      <textarea onChange={(e:any) => {setContent(e.target.value)}} value={content} placeholder='Blog Content...' ></textarea>
      <button onClick={addBlog}>Post Blog!</button>
    </div>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 Buzzbloggers
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
           - All Rights Reserved. Made by Ehsan Saleem
        </a>
      </footer>
    </div>
  )
}

export default Write
